version: 2.1

description:
  This orb enables you to execute TestCraft test automation scenarios and view their results through CircleCI’s CI/CD platform.


# This information will be displayed in the orb registry and is not mandatory.
display:
  home_url: "https://www.testcraft.io/"
  source_url: "https://github.com/test-craft/tc-cli-orb"

orbs:
  node: circleci/node@3.0.1

jobs:
    run:
      docker: 
        - image: 'cimg/base:stable'
      parameters:
        user_mail:
          description: your user mail
          type: string
        auth_token:
          description: Unique identifier of the organization. Can be retrieved from the CI/CD integration page in any suite in your TestCrafts account
          type: string
        project:
          description: The name of the project that contains the test suite your test suite
          type: string
        version:
           description: the projects version
           type: string
           default: "Base"
        suite:
            description: The suites' name
            type: string
        platform:
            description: The platforms name where to run the test
            type: string
        environment:
            description: The environment name
            type: string
      steps:
        - node/install:
            install-yarn: true
            node-version: latest
        - run:
            name: install tc-cli
            command: sudo npm install -g tc-cli
        - run:
            name: run suite
            command: |
              tc-cli run -u  "<< parameters.user_mail >>" -t  "<< parameters.auth_token >>" -p "<< parameters.project >>" -v "<< parameters.version >>" -s "<< parameters.suite >>" -l "<< parameters.platform >>" -e "<< parameters.environment >>"

